# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import dataclasses
import datetime
from typing import Any, Optional


@dataclasses.dataclass()
class Invite:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Optional[Any]
    user_id: str
    code_hash: str
    expires_at: datetime.datetime
    accepted_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class Session:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Optional[Any]
    user_id: str
    tenant_id: Optional[str]
    last_seen_at: datetime.datetime
    expired_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class Tenant:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Optional[Any]
    name: str
    inbound_source: str


@dataclasses.dataclass()
class TenantsInboundSourceEnum:
    value: str


@dataclasses.dataclass()
class TenantsUser:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Optional[Any]
    user_id: str
    tenant_id: str
    removed_at: Optional[datetime.datetime]
    removed_by_user: Optional[str]


@dataclasses.dataclass()
class User:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Optional[Any]
    name: str
    email: str
    password_hash: Optional[str]
    signup_step: str
    is_enabled: bool
    last_visited_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class UserSignupStepEnum:
    value: str


@dataclasses.dataclass()
class VaultedSecret:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Optional[Any]
    tenant_id: str
    ciphertext: str
