# Code generated by sqlc. DO NOT EDIT.
import dataclasses
import datetime
from typing import Any

@dataclasses.dataclass(slots=True)
class UserSignupStepEnum:
    value: str

@dataclasses.dataclass(slots=True)
class User:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Any | None
    name: str
    email: str
    password_hash: str | None
    signup_step: str
    is_enabled: bool
    last_visited_at: datetime.datetime | None

@dataclasses.dataclass(slots=True)
class Invite:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Any | None
    user_id: str
    code_hash: str
    expires_at: datetime.datetime
    accepted_at: datetime.datetime | None

@dataclasses.dataclass(slots=True)
class OrganizationsInboundSourceEnum:
    value: str

@dataclasses.dataclass(slots=True)
class Organization:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Any | None
    name: str
    inbound_source: str

@dataclasses.dataclass(slots=True)
class OrganizationsUser:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Any | None
    user_id: str
    organization_id: str
    removed_at: datetime.datetime | None
    removed_by_user: str | None

@dataclasses.dataclass(slots=True)
class Session:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Any | None
    user_id: str
    organization_id: str | None
    last_seen_at: datetime.datetime
    expired_at: datetime.datetime | None

@dataclasses.dataclass(slots=True)
class VaultedSecret:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: Any | None
    organization_id: str
    ciphertext: str

