# Code generated by sqlc. DO NOT EDIT.
import dataclasses
import datetime
from typing import Any

from database.__codegen__ import enums
@dataclasses.dataclass(slots=True)
class InviteModel:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: dict[str, Any] | None
    user_id: str
    code_hash: str
    expires_at: datetime.datetime
    accepted_at: datetime.datetime | None

@dataclasses.dataclass(slots=True)
class UserModel:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: dict[str, Any] | None
    name: str
    email: str
    password_hash: str | None
    signup_step: enums.UserSignupStepEnum
    is_enabled: bool
    last_visited_at: datetime.datetime | None

@dataclasses.dataclass(slots=True)
class OrganizationModel:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: dict[str, Any] | None
    name: str
    inbound_source: enums.OrganizationsInboundSourceEnum

@dataclasses.dataclass(slots=True)
class OrganizationsUserModel:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: dict[str, Any] | None
    user_id: str
    organization_id: str
    removed_at: datetime.datetime | None
    removed_by_user: str | None

@dataclasses.dataclass(slots=True)
class SessionModel:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: dict[str, Any] | None
    user_id: str
    organization_id: str | None
    last_seen_at: datetime.datetime
    expired_at: datetime.datetime | None

@dataclasses.dataclass(slots=True)
class VaultedSecretModel:
    id: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    storytime: dict[str, Any] | None
    organization_id: str
    ciphertext: str

@dataclasses.dataclass(slots=True)
class YoyoLockModel:
    locked: int
    ctime: datetime.datetime | None
    pid: int

