# Code generated by python/tools/codegen_db. DO NOT EDIT.

from typing import Literal

type DatabaseTablePrefixEnum = Literal["usr", "inv", "org", "utn", "ses", "vsc"]

DATABASE_TABLE_PREFIX_MAP: dict[DatabaseTablePrefixEnum, str] = {
    "usr": "users",
    "inv": "invites",
    "org": "organizations",
    "utn": "organizations_users",
    "ses": "sessions",
    "vsc": "vaulted_secrets",
}
