# Code generated by python/tools/codegen-db. DO NOT EDIT.

DATABASE_TABLE_PREFIXES = {
    "usr": "users",
    "inv": "invites",
    "org": "organizations",
    "utn": "organizations_users",
    "ses": "sessions",
    "vsc": "vaulted_secrets",
}
