/* Code generated by python/tools/codegen_rpc. DO NOT EDIT. */

import type { Dayjs } from "dayjs";

/**
 * All Errors
 */

export type RPCErrors = {
	UnauthorizedError: null;
	ServerJSONDeserializeError: {
		message: string;
	};
	InputValidationError: {
		message: string;
		fields: Record<string, unknown>;
	};
	InvalidCredentialsError: null;
	AuthOrganizationNotFoundError: null;
	// These are errors that the frontend RPC executor can raise.
	NetworkError: null;
	InternalServerError: null;
	RPCNotFoundError: null;
	ClientJSONDecodeError: null;
	UncaughtRPCError: null;
};

/**
 * System Errors
 */

export type RPCSystemErrors =
	| "NetworkError"
	| "InternalServerError"
	| "RPCNotFoundError"
	| "ClientJSONDecodeError"
	| "UncaughtRPCError"
	| "UnauthorizedError"
	| "ServerJSONDeserializeError"
	| "InputValidationError";

/**
 * Nested & Common
 */

export type GetPageLoadInfoUser = {
	id: string;
	name: string;
	email: string;
};

export type GetPageLoadInfoOrganization = {
	id: string;
	name: string;
};

/**
 * RPC I/O
 */

export type RPCs = {
	init: {
		in: null;
		out: {
			user: GetPageLoadInfoUser | null;
			organization: GetPageLoadInfoOrganization | null;
			available_organizations: GetPageLoadInfoOrganization[];
		};
		errors: never;
	};
	login: {
		in: {
			email: string;
			password: string;
			permanent: boolean;
			organization_id: string | null;
		};
		out: null;
		errors: "InvalidCredentialsError" | "AuthOrganizationNotFoundError";
	};
	logout: {
		in: null;
		out: null;
		errors: never;
	};
};

/**
 * RPC Methods
 */

export const RPCMethods: Record<keyof RPCs, "GET" | "POST"> = {
	init: "GET",
	login: "POST",
	logout: "POST",
};
