# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: codegen.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List, Optional

import betterproto
import grpclib


@dataclass
class File(betterproto.Message):
    name: str = betterproto.string_field(1)
    contents: bytes = betterproto.bytes_field(2)


@dataclass
class Settings(betterproto.Message):
    version: str = betterproto.string_field(1)
    engine: str = betterproto.string_field(2)
    schema: List[str] = betterproto.string_field(3)
    queries: List[str] = betterproto.string_field(4)
    codegen: "Codegen" = betterproto.message_field(12)


@dataclass
class Codegen(betterproto.Message):
    out: str = betterproto.string_field(1)
    plugin: str = betterproto.string_field(2)
    options: bytes = betterproto.bytes_field(3)
    env: List[str] = betterproto.string_field(4)
    process: "CodegenProcess" = betterproto.message_field(5)
    wasm: "CodegenWASM" = betterproto.message_field(6)


@dataclass
class CodegenProcess(betterproto.Message):
    cmd: str = betterproto.string_field(1)


@dataclass
class CodegenWASM(betterproto.Message):
    url: str = betterproto.string_field(1)
    sha256: str = betterproto.string_field(2)


@dataclass
class Catalog(betterproto.Message):
    comment: str = betterproto.string_field(1)
    default_schema: str = betterproto.string_field(2)
    name: str = betterproto.string_field(3)
    schemas: List["Schema"] = betterproto.message_field(4)


@dataclass
class Schema(betterproto.Message):
    comment: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    tables: List["Table"] = betterproto.message_field(3)
    enums: List["Enum"] = betterproto.message_field(4)
    composite_types: List["CompositeType"] = betterproto.message_field(5)


@dataclass
class CompositeType(betterproto.Message):
    name: str = betterproto.string_field(1)
    comment: str = betterproto.string_field(2)


@dataclass
class Enum(betterproto.Message):
    name: str = betterproto.string_field(1)
    vals: List[str] = betterproto.string_field(2)
    comment: str = betterproto.string_field(3)


@dataclass
class Table(betterproto.Message):
    rel: "Identifier" = betterproto.message_field(1)
    columns: List["Column"] = betterproto.message_field(2)
    comment: str = betterproto.string_field(3)


@dataclass
class Identifier(betterproto.Message):
    catalog: str = betterproto.string_field(1)
    schema: str = betterproto.string_field(2)
    name: str = betterproto.string_field(3)


@dataclass
class Column(betterproto.Message):
    name: str = betterproto.string_field(1)
    not_null: bool = betterproto.bool_field(3)
    is_array: bool = betterproto.bool_field(4)
    comment: str = betterproto.string_field(5)
    length: int = betterproto.int32_field(6)
    is_named_param: bool = betterproto.bool_field(7)
    is_func_call: bool = betterproto.bool_field(8)
    # XXX: Figure out what PostgreSQL calls `foo.id`
    scope: str = betterproto.string_field(9)
    table: "Identifier" = betterproto.message_field(10)
    table_alias: str = betterproto.string_field(11)
    type: "Identifier" = betterproto.message_field(12)
    is_sqlc_slice: bool = betterproto.bool_field(13)
    embed_table: "Identifier" = betterproto.message_field(14)
    original_name: str = betterproto.string_field(15)
    unsigned: bool = betterproto.bool_field(16)
    array_dims: int = betterproto.int32_field(17)


@dataclass
class Query(betterproto.Message):
    text: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    cmd: str = betterproto.string_field(3)
    columns: List["Column"] = betterproto.message_field(4)
    params: List["Parameter"] = betterproto.message_field(5)
    comments: List[str] = betterproto.string_field(6)
    filename: str = betterproto.string_field(7)
    insert_into_table: "Identifier" = betterproto.message_field(8)


@dataclass
class Parameter(betterproto.Message):
    number: int = betterproto.int32_field(1)
    column: "Column" = betterproto.message_field(2)


@dataclass
class GenerateRequest(betterproto.Message):
    settings: "Settings" = betterproto.message_field(1)
    catalog: "Catalog" = betterproto.message_field(2)
    queries: List["Query"] = betterproto.message_field(3)
    sqlc_version: str = betterproto.string_field(4)
    plugin_options: bytes = betterproto.bytes_field(5)
    global_options: bytes = betterproto.bytes_field(6)


@dataclass
class GenerateResponse(betterproto.Message):
    files: List["File"] = betterproto.message_field(1)


class CodegenServiceStub(betterproto.ServiceStub):
    async def generate(
        self,
        *,
        settings: Optional["Settings"] = None,
        catalog: Optional["Catalog"] = None,
        queries: List["Query"] = [],
        sqlc_version: str = "",
        plugin_options: bytes = b"",
        global_options: bytes = b"",
    ) -> GenerateResponse:
        request = GenerateRequest()
        if settings is not None:
            request.settings = settings
        if catalog is not None:
            request.catalog = catalog
        if queries is not None:
            request.queries = queries
        request.sqlc_version = sqlc_version
        request.plugin_options = plugin_options
        request.global_options = global_options

        return await self._unary_unary(
            "/plugin.CodegenService/Generate",
            request,
            GenerateResponse,
        )
