# Code generated by sqlc. DO NOT EDIT.
import dataclasses
import datetime
from typing import Any, AsyncIterator
import sqlalchemy
import psycopg
from database.conn import DBConn
from database.__codegen_db__ import models
from foundation.observability.errors import NotFoundError

@dataclasses.dataclass(slots=True)
class PipelineOrganizationIdFetchAllResult:
    id: str

PIPELINE_ORGANIZATION_ID_FETCH_ALL = """\
SELECT id FROM organizations ORDER BY id
"""

async def query_pipeline_organization_id_fetch_all(conn: DBConn) -> AsyncIterator[PipelineOrganizationIdFetchAllResult]:
    result = await conn.execute(sqlalchemy.text(PIPELINE_ORGANIZATION_ID_FETCH_ALL), {})
    for row in result:
        yield PipelineOrganizationIdFetchAllResult(
            id=row[0],
        )

