-- TODO: Not done.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'product') THEN
    CREATE ROLE product NOLOGIN;
  END IF;
END $$;

GRANT CONNECT ON DATABASE product TO product;
GRANT USAGE ON SCHEMA public TO product;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO product;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO product;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO product;

-- Future objects default privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO product;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO product;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO product;

GRANT product TO "<service-account-email>";
