# Code generated by sqlc. DO NOT EDIT.
from typing import Literal

type OrganizationsInboundSourceEnum = Literal["organic", "outreach", "referral", "unknown", "word_of_mouth"]
ORGANIZATIONS_INBOUND_SOURCE_ENUM_VALUES = ['organic', 'outreach', 'referral', 'unknown', 'word_of_mouth']

type UserSignupStepEnum = Literal["complete", "created"]
USER_SIGNUP_STEP_ENUM_VALUES = ['complete', 'created']

