name: python
on: 
  push:
    paths:
      - .github/workflows/python.yaml
      - flake.*
      - python/**
      - infra/deploys/**
      - '!**/*.md'
defaults:
  run:
    working-directory: python/
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v15
        with:
          name: blossom
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Nix
        run: nix build -j8 ../infra/dev-shell/#devShells.x86_64-linux.python
      - name: Start Postgres
        run: docker compose up postgres -d
      - name: Install dependencies
        run: nix develop ../infra/dev-shell/#devShells.x86_64-linux.python --command just install
      - name: Lint
        if: success() || failure()
        run: nix develop ../infra/dev-shell/#devShells.x86_64-linux.python --command just lint
      - name: Test
        if: success() || failure()
        run: nix develop ../infra/dev-shell/#devShells.x86_64-linux.python --command just test
      - name: Migrate & Codegen
        if: success() || failure()
        run: |
          nix develop ../infra/dev-shell/#devShells.x86_64-linux.python --command just codegen-db
          nix develop ../infra/dev-shell/#devShells.x86_64-linux.python --command just codegen-rpc
      - name: Diff
        if: success() || failure()
        run: nix develop ../infra/dev-shell/#devShells.x86_64-linux.python --command just diff
